export const preview1InitialState = {
  userAvatarUrl:
    "https://www.figma.com/api/mcp/asset/62fe1d3a-a61f-4070-a0b6-61bfc23bedf6",
  searchQuery: "",
  statusFilter: "all",
  priorityFilter: "all",
  sortKey: "titleSort",
  sortDir: "asc",
  currentPage: 1,
  rowsPerPage: 10,
  selectedTaskIds: [] as string[],
  nextTaskNumber: 9720,
  tasks: [
    {
      id: "TASK-8782",
      taskOrder: 8782,
      type: "Documentation",
      title: "You can't compress the program without quantifying the open-source SSD matrix.",
      titleSort:
        "You can't compress the program without quantifying the open-source SSD matrix.",
      status: "In Progress",
      statusOrder: 2,
      priority: "Medium",
      priorityOrder: 2,
      priorityIcon: "right",
    },
    {
      id: "TASK-1138",
      taskOrder: 1138,
      type: "Feature",
      title: "Generating the driver won't do anything, we need to quantify the 1080p SMTP monitor.",
      titleSort:
        "Generating the driver won't do anything, we need to quantify the 1080p SMTP monitor.",
      status: "In Progress",
      statusOrder: 2,
      priority: "Medium",
      priorityOrder: 2,
      priorityIcon: "right",
    },
    {
      id: "TASK-8404",
      taskOrder: 8404,
      type: "Documentation",
      title: "Calculating the bus won't do anything, we need to navigate the back-end alarm.",
      titleSort:
        "Calculating the bus won't do anything, we need to navigate the back-end alarm.",
      status: "In Progress",
      statusOrder: 2,
      priority: "High",
      priorityOrder: 3,
      priorityIcon: "up",
    },
    {
      id: "TASK-5365",
      taskOrder: 5365,
      type: "Bug",
      title: "We need to generate the virtual HEX alarm!",
      titleSort: "We need to generate the virtual HEX alarm!",
      status: "In Progress",
      statusOrder: 2,
      priority: "Low",
      priorityOrder: 1,
      priorityIcon: "down",
    },
    {
      id: "TASK-1024",
      taskOrder: 1024,
      type: "Documentation",
      title: "Backing up the pixel won't do anything, we need to transmit the primary layer.",
      titleSort:
        "Backing up the pixel won't do anything, we need to transmit the primary layer.",
      status: "In Progress",
      statusOrder: 2,
      priority: "Low",
      priorityOrder: 1,
      priorityIcon: "down",
    },
    {
      id: "TASK-1571",
      taskOrder: 1571,
      type: "Documentation",
      title: "Overriding the microchip won't do anything, we need to transmit the digital bus.",
      titleSort:
        "Overriding the microchip won't do anything, we need to transmit the digital bus.",
      status: "In Progress",
      statusOrder: 2,
      priority: "Low",
      priorityOrder: 1,
      priorityIcon: "down",
    },
    {
      id: "TASK-8484",
      taskOrder: 8484,
      type: "Feature",
      title: "I'll input the neural DRAM circuit, that should protocol the SMTP interface!",
      titleSort:
        "I'll input the neural DRAM circuit, that should protocol the SMTP interface!",
      status: "In Progress",
      statusOrder: 2,
      priority: "Medium",
      priorityOrder: 2,
      priorityIcon: "right",
    },
    {
      id: "TASK-9616",
      taskOrder: 9616,
      type: "Bug",
      title: "We need to parse the solid state UDP firewall!",
      titleSort: "We need to parse the solid state UDP firewall!",
      status: "In Progress",
      statusOrder: 2,
      priority: "Low",
      priorityOrder: 1,
      priorityIcon: "down",
    },
    {
      id: "TASK-4920",
      taskOrder: 4920,
      type: "Feature",
      title: "We need to synthesize the cross-platform ASCII pixel!",
      titleSort: "We need to synthesize the cross-platform ASCII pixel!",
      status: "In Progress",
      statusOrder: 2,
      priority: "Medium",
      priorityOrder: 2,
      priorityIcon: "right",
    },
    {
      id: "TASK-5168",
      taskOrder: 5168,
      type: "Bug",
      title: "Bypassing the hard drive won't do anything, we need to input the bluetooth matrix.",
      titleSort:
        "Bypassing the hard drive won't do anything, we need to input the bluetooth matrix.",
      status: "In Progress",
      statusOrder: 2,
      priority: "High",
      priorityOrder: 3,
      priorityIcon: "up",
    },
    {
      id: "TASK-7712",
      taskOrder: 7712,
      type: "Documentation",
      title: "We need to program the optical panel so the support team can review the workflow.",
      titleSort:
        "We need to program the optical panel so the support team can review the workflow.",
      status: "Todo",
      statusOrder: 1,
      priority: "Medium",
      priorityOrder: 2,
      priorityIcon: "right",
    },
    {
      id: "TASK-6621",
      taskOrder: 6621,
      type: "Feature",
      title: "Quantify the mobile circuit and ship a cleaner backlog handoff for the release.",
      titleSort:
        "Quantify the mobile circuit and ship a cleaner backlog handoff for the release.",
      status: "Done",
      statusOrder: 3,
      priority: "Low",
      priorityOrder: 1,
      priorityIcon: "down",
    },
  ],
};

