export const preview3InitialState = {
  headerTitle: "Dashboard",
  headerActionLabel: "View in Shadcn",
  sectionTitle: "Documents",
  activeChartRange: "last3Months",
  activeDocumentTab: "outline",
  currentPage: 1,
  rowsPerPage: "10",
  selectedRowIds: [] as string[],
  reviewerOptions: ["Eddie Lake", "Jamik Tashpulatov", "Ava Johnson"],
  topNav: [
    { id: "dashboard", label: "Dashboard", icon: "LayoutGrid" },
    { id: "lifecycle", label: "Lifecycle", icon: "Layers" },
    { id: "analytics", label: "Analytics", icon: "BarChart2" },
    { id: "projects", label: "Projects", icon: "FolderKanban" },
    { id: "team", label: "Team", icon: "Users" },
  ],
  documentNav: [
    { id: "data-library", label: "Data Library", icon: "CreditCard" },
    { id: "reports", label: "Reports", icon: "BarChart2" },
    { id: "word-assistant", label: "Word Assistant", icon: "MessageSquare" },
    { id: "more", label: "More", icon: "MoreHorizontalIcon" },
  ],
  footerNav: [
    { id: "settings", label: "Settings", icon: "Wrench" },
    { id: "help", label: "Get Help", icon: "InfoIcon" },
    { id: "search", label: "Search", icon: "SearchIcon" },
  ],
  metrics: [
    {
      id: "revenue",
      label: "Total Revenue",
      trend: "+12.5%",
      trendDirection: "up",
      value: "$1,250.00",
      summary: "Trending up this month",
      caption: "Visitors for the last 6 months",
    },
    {
      id: "customers",
      label: "New Customers",
      trend: "-20%",
      trendDirection: "down",
      value: "1,234",
      summary: "Down 20% this period",
      caption: "Acquisition needs attention",
    },
    {
      id: "accounts",
      label: "Active Accounts",
      trend: "+12.5%",
      trendDirection: "up",
      value: "45,678",
      summary: "Strong user retention",
      caption: "Engagement exceed targets",
    },
    {
      id: "growth",
      label: "Growth Rate",
      trend: "+4.5%",
      trendDirection: "up",
      value: "4.5%",
      summary: "Steady performance...",
      caption: "Meets growth projections",
    },
  ],
  chartLabels: [
    "Apr 2",
    "Apr 8",
    "Apr 14",
    "Apr 21",
    "Apr 28",
    "May 5",
    "May 12",
    "May 19",
    "May 25",
    "Jun 2",
    "Jun 8",
    "Jun 15",
    "Jun 22",
    "Jun 30",
  ],
  chartSeriesByRange: {
    last3Months: [
      { label: "Apr 2", visitors: 86, baseline: 46 },
      { label: "Apr 8", visitors: 54, baseline: 28 },
      { label: "Apr 14", visitors: 24, baseline: 18 },
      { label: "Apr 21", visitors: 20, baseline: 16 },
      { label: "Apr 28", visitors: 32, baseline: 20 },
      { label: "May 5", visitors: 56, baseline: 28 },
      { label: "May 12", visitors: 80, baseline: 38 },
      { label: "May 19", visitors: 96, baseline: 44 },
      { label: "May 25", visitors: 88, baseline: 40 },
      { label: "Jun 2", visitors: 58, baseline: 28 },
      { label: "Jun 8", visitors: 26, baseline: 14 },
      { label: "Jun 15", visitors: 18, baseline: 12 },
      { label: "Jun 22", visitors: 34, baseline: 22 },
      { label: "Jun 30", visitors: 76, baseline: 38 },
    ],
    last30Days: [
      { label: "Apr 2", visitors: 42, baseline: 24 },
      { label: "Apr 8", visitors: 56, baseline: 30 },
      { label: "Apr 14", visitors: 38, baseline: 22 },
      { label: "Apr 21", visitors: 52, baseline: 28 },
      { label: "Apr 28", visitors: 64, baseline: 34 },
      { label: "May 5", visitors: 58, baseline: 30 },
      { label: "May 12", visitors: 72, baseline: 36 },
      { label: "May 19", visitors: 80, baseline: 40 },
      { label: "May 25", visitors: 68, baseline: 34 },
      { label: "Jun 2", visitors: 60, baseline: 32 },
      { label: "Jun 8", visitors: 48, baseline: 26 },
      { label: "Jun 15", visitors: 36, baseline: 20 },
      { label: "Jun 22", visitors: 52, baseline: 28 },
      { label: "Jun 30", visitors: 66, baseline: 34 },
    ],
    last7Days: [
      { label: "Apr 2", visitors: 18, baseline: 8 },
      { label: "Apr 8", visitors: 24, baseline: 12 },
      { label: "Apr 14", visitors: 28, baseline: 14 },
      { label: "Apr 21", visitors: 22, baseline: 12 },
      { label: "Apr 28", visitors: 32, baseline: 16 },
      { label: "May 5", visitors: 40, baseline: 22 },
      { label: "May 12", visitors: 48, baseline: 26 },
      { label: "May 19", visitors: 52, baseline: 28 },
      { label: "May 25", visitors: 46, baseline: 24 },
      { label: "Jun 2", visitors: 38, baseline: 20 },
      { label: "Jun 8", visitors: 26, baseline: 14 },
      { label: "Jun 15", visitors: 20, baseline: 10 },
      { label: "Jun 22", visitors: 30, baseline: 16 },
      { label: "Jun 30", visitors: 44, baseline: 22 },
    ],
  },
  chartRanges: [
    { id: "last3Months", label: "Last 3 months" },
    { id: "last30Days", label: "Last 30 days" },
    { id: "last7Days", label: "Last 7 days" },
  ],
  documentTabs: [
    { id: "outline", label: "Outline", count: null },
    { id: "pastPerformance", label: "Past Performance", count: 3 },
    { id: "keyPersonnel", label: "Key Personnel", count: 2 },
    { id: "focusDocuments", label: "Focus Documents", count: null },
  ],
  outlineRows: [
    {
      id: "cover-page",
      tab: "outline",
      title: "Cover page",
      sectionType: "Cover page",
      status: "In Process",
      target: 18,
      limit: 5,
      reviewer: "Eddie Lake",
      needsReviewer: false,
    },
    {
      id: "toc",
      tab: "outline",
      title: "Table of contents",
      sectionType: "Table of contents",
      status: "Done",
      target: 29,
      limit: 24,
      reviewer: "Eddie Lake",
      needsReviewer: false,
    },
    {
      id: "executive-summary",
      tab: "outline",
      title: "Executive summary",
      sectionType: "Narrative",
      status: "Done",
      target: 10,
      limit: 13,
      reviewer: "Eddie Lake",
      needsReviewer: false,
    },
    {
      id: "technical-approach",
      tab: "outline",
      title: "Technical approach",
      sectionType: "Narrative",
      status: "Done",
      target: 27,
      limit: 23,
      reviewer: "Jamik Tashpulatov",
      needsReviewer: false,
    },
    {
      id: "design",
      tab: "outline",
      title: "Design",
      sectionType: "Narrative",
      status: "In Process",
      target: 2,
      limit: 16,
      reviewer: "Jamik Tashpulatov",
      needsReviewer: false,
    },
    {
      id: "capabilities",
      tab: "outline",
      title: "Capabilities",
      sectionType: "Narrative",
      status: "In Process",
      target: 20,
      limit: 8,
      reviewer: "Jamik Tashpulatov",
      needsReviewer: false,
    },
    {
      id: "integration",
      tab: "outline",
      title: "Integration with existing systems",
      sectionType: "Narrative",
      status: "In Process",
      target: 19,
      limit: 21,
      reviewer: "Jamik Tashpulatov",
      needsReviewer: false,
    },
    {
      id: "innovation",
      tab: "outline",
      title: "Innovation and Advantages",
      sectionType: "Narrative",
      status: "Done",
      target: 25,
      limit: 26,
      reviewer: "Assign reviewer",
      needsReviewer: true,
    },
    {
      id: "overview",
      tab: "outline",
      title: "Overview of EMR's Innovative Solutions",
      sectionType: "Technical content",
      status: "Done",
      target: 7,
      limit: 23,
      reviewer: "Assign reviewer",
      needsReviewer: true,
    },
    {
      id: "algorithms",
      tab: "outline",
      title: "Advanced Algorithms and Machine Learning",
      sectionType: "Narrative",
      status: "Done",
      target: 30,
      limit: 28,
      reviewer: "Assign reviewer",
      needsReviewer: true,
    },
  ],
  totalRows: 68,
  totalPages: 7,
};

