// apps/example/src/pages/eg2/initial-state.ts
export const eg2InitialState = {
    sidebarOpen: true,
    activeNav: "data-library",
    activeHeading: "Documents",
    chartRange: "90d",
    tableQuery: "",
    page: 0,
    pageSize: "5",
    selectedIds: [] as string[],
    metrics: [
      {
        id: "revenue",
        label: "Total Revenue",
        value: "$1,250.00",
        delta: "+12.5%",
        tone: "up",
        summary: "Trending up this month",
        detail: "Visitors for the last 6 months",
      },
      {
        id: "customers",
        label: "New Customers",
        value: "1,234",
        delta: "-20%",
        tone: "down",
        summary: "Down 20% this period",
        detail: "Acquisition needs attention",
      },
      {
        id: "accounts",
        label: "Active Accounts",
        value: "45,678",
        delta: "+12.5%",
        tone: "up",
        summary: "Strong user retention",
        detail: "Engagement exceeds targets",
      },
      {
        id: "growth",
        label: "Growth Rate",
        value: "4.5%",
        delta: "+4.5%",
        tone: "up",
        summary: "Steady performance increase",
        detail: "Meets growth projections",
      },
    ],
    chartRanges: [
      {
        id: "90d",
        label: "Last 3 months",
        total: "126,420",
        subtitle: "Total visitors for the last 3 months",
        points: [
          { label: "Apr 2", desktopPct: 42, mobilePct: 58 },
          { label: "Apr 8", desktopPct: 48, mobilePct: 62 },
          { label: "Apr 14", desktopPct: 54, mobilePct: 69 },
          { label: "Apr 21", desktopPct: 66, mobilePct: 76 },
          { label: "Apr 28", desktopPct: 72, mobilePct: 82 },
          { label: "May 5", desktopPct: 58, mobilePct: 68 },
          { label: "May 12", desktopPct: 63, mobilePct: 79 },
          { label: "May 19", desktopPct: 70, mobilePct: 84 },
          { label: "May 25", desktopPct: 74, mobilePct: 88 },
          { label: "Jun 2", desktopPct: 60, mobilePct: 73 },
          { label: "Jun 8", desktopPct: 68, mobilePct: 81 },
          { label: "Jun 15", desktopPct: 77, mobilePct: 92 },
        ],
      },
      {
        id: "30d",
        label: "Last 30 days",
        total: "48,980",
        subtitle: "Faster growth from recent campaigns",
        points: [
          { label: "Week 1", desktopPct: 38, mobilePct: 54 },
          { label: "Week 2", desktopPct: 52, mobilePct: 66 },
          { label: "Week 3", desktopPct: 61, mobilePct: 76 },
          { label: "Week 4", desktopPct: 74, mobilePct: 88 },
        ],
      },
      {
        id: "7d",
        label: "Last 7 days",
        total: "11,270",
        subtitle: "Daily visitors this week",
        points: [
          { label: "Mon", desktopPct: 34, mobilePct: 48 },
          { label: "Tue", desktopPct: 40, mobilePct: 56 },
          { label: "Wed", desktopPct: 57, mobilePct: 69 },
          { label: "Thu", desktopPct: 49, mobilePct: 63 },
          { label: "Fri", desktopPct: 66, mobilePct: 80 },
          { label: "Sat", desktopPct: 73, mobilePct: 88 },
          { label: "Sun", desktopPct: 59, mobilePct: 71 },
        ],
      },
    ],
    reviewers: [
      "Assign reviewer",
      "Jamik Tashpulatov",
      "Monica Clark",
      "Sofia Chen",
      "Arjun Rao",
    ],
    reviews: [
      {
        id: "row-1",
        title: "Executive summary and positioning",
        type: "Narrative",
        status: "in-progress",
        tasks: 20,
        score: 8,
        reviewer: "Jamik Tashpulatov",
      },
      {
        id: "row-2",
        title: "Integration with existing systems",
        type: "Narrative",
        status: "in-progress",
        tasks: 19,
        score: 21,
        reviewer: "Jamik Tashpulatov",
      },
      {
        id: "row-3",
        title: "Innovation and Advantages",
        type: "Narrative",
        status: "done",
        tasks: 25,
        score: 26,
        reviewer: "Assign reviewer",
      },
      {
        id: "row-4",
        title: "Overview of EMR's Innovative Solutions",
        type: "Technical content",
        status: "done",
        tasks: 7,
        score: 23,
        reviewer: "Assign reviewer",
      },
      {
        id: "row-5",
        title: "Advanced Algorithms and Machine Learning",
        type: "Narrative",
        status: "done",
        tasks: 30,
        score: 28,
        reviewer: "Assign reviewer",
      },
      {
        id: "row-6",
        title: "Platform architecture and deployment model",
        type: "Technical content",
        status: "in-progress",
        tasks: 14,
        score: 17,
        reviewer: "Monica Clark",
      },
      {
        id: "row-7",
        title: "Security, compliance, and governance",
        type: "Narrative",
        status: "done",
        tasks: 18,
        score: 19,
        reviewer: "Sofia Chen",
      },
      {
        id: "row-8",
        title: "Commercial packaging and pricing strategy",
        type: "Narrative",
        status: "in-progress",
        tasks: 11,
        score: 12,
        reviewer: "Arjun Rao",
      },
    ],
  } as const;
  